#!/usr/bin/env python
"""Side-by-side of the corrected and legacy conventions for every observable.

Writes comparison.md. Run after regenerate.py.
"""
import os
import sys

import numpy as np

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from src import analysis, io

OUT = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'comparison.md')


def main():
    ens = {}
    for size in io.SIZES:
        try:
            ens[size] = analysis.SizeEnsemble(size)
        except RuntimeError as exc:
            print(f'skipping {size}: {exc}')

    L = []
    w = L.append
    w('# Corrected vs legacy conventions\n')
    w('Generated by `compare_conventions.py` from the cached observables in '
      '`data/observables/`. Boltzmann weighted at T = 2000 K, Si-O cutoff 2.0 A.\n')

    w('## Ensembles\n')
    w('| size | structures | effective N | density (at/A^3) |')
    w('|---|---|---|---|')
    for s, e in ens.items():
        w(f'| {s}-atom | {len(e)} | {e.n_eff:.0f} | {e.density:.4f} |')
    w('')

    w('## Q^n speciation\n')
    w('Legacy counted any O with >=1 other Si as bridging and silently dropped Si with '
      '5+ bridging O, so its fractions do not sum to 1.\n')
    for s, e in ens.items():
        new, old = e.qn_fractions(False), e.qn_fractions(True)
        w(f'**{s}-atom**\n')
        w('| Q^n | corrected | legacy |')
        w('|---|---|---|')
        for n in range(len(new)):
            if new[n] > 1e-4 or old[n] > 1e-4:
                w(f'| Q{n} | {100*new[n]:.1f}% | {100*old[n]:.1f}% |')
        w(f'| **non-Q4** | **{100*(new.sum()-new[4]):.1f}%** | {100*(old.sum()-old[4]):.1f}% |')
        w(f'| sum | {100*new.sum():.1f}% | {100*old.sum():.1f}% |')
        w('')

    w('## Bond angles\n')
    w('Legacy used the law of cosines on three independently minimum-imaged distances, '
      'which can mix periodic images; corrected uses the true displacement vectors.\n')
    w('| size | kind | corrected peak / mean / sigma | legacy peak / mean / sigma |')
    w('|---|---|---|---|')
    for s, e in ens.items():
        for kind in ('si_o_si', 'o_si_o'):
            a, b = e.bad_moments(kind, False), e.bad_moments(kind, True)
            w(f'| {s} | {kind} | {a["peak"]:.1f} / {a["mean"]:.1f} / {a["std"]:.1f} '
              f'| {b["peak"]:.1f} / {b["mean"]:.1f} / {b["std"]:.1f} |')
    w('')
    w('Reference: Si-O-Si 136-142 deg (Sarnthein 1995, PBE-MD), 151 +/- 11 deg '
      '(Mauri 2000, NMR); O-Si-O 109.5 deg.\n')

    w('## Ring statistics\n')
    w('`RC_local` = unique rings per Si excluding rings that close through a periodic '
      'image of an atom already on the ring. `RC` includes them. `RN` counts each ring '
      'once per Si it touches, so RN ~ n x RC — this is what the draft was reporting as '
      'R_N. Rino 1993 uses rings per Si, i.e. the RC family.\n')
    for s, e in ens.items():
        rc_local, rc, rn = e.rings('RC_local'), e.rings('RC'), e.rings('RN')
        frac = e.self_image_fraction()
        sizes = sorted(set(rc) | set(rn))
        w(f'**{s}-atom**\n')
        w('| n | RC_local (corrected) | RC (all) | RN (draft) | self-image share |')
        w('|---|---|---|---|---|')
        for n in sizes:
            if max(rc_local.get(n, 0), rc.get(n, 0), rn.get(n, 0)) < 1e-3:
                continue
            w(f'| {n} | {rc_local.get(n,0):.3f} | {rc.get(n,0):.3f} | '
              f'{rn.get(n,0):.3f} | {100*frac.get(n,0):.0f}% |')
        w('')
        w(f'2MR per cell: {e.mean_2mr_per_cell("RC_local"):.2f} '
          f'(draft RN convention: {e.rings("RN").get(2,0)*(s//3):.2f})\n')

    w('## Coordination\n')
    w('| size | Si CN distribution (0..6) | O CN distribution (0..4) |')
    w('|---|---|---|')
    for s, e in ens.items():
        si = e.coordination('Si')[:7]
        ox = e.coordination('O')[:5]
        w(f'| {s} | {" ".join(f"{100*x:.1f}" for x in si)} | '
          f'{" ".join(f"{100*x:.1f}" for x in ox)} |')
    w('')

    w('## Structure factor\n')
    w('S(q) is now evaluated exactly on each cell\'s reciprocal lattice. '
      'RMSD against Grimley 1990 on q(S(q)-1):\n')
    ref = _grimley()
    if ref is not None:
        g_q, g_y = ref
        w('| size | RMSD q in [1,10] | RMSD FSDP [1.2,2.0] | FSDP position |')
        w('|---|---|---|---|')
        for s, e in ens.items():
            q, S = e.structure_factor()
            y = q * (S - 1)
            m = np.isfinite(y)
            def rmsd(lo, hi):
                k = m & (q >= lo) & (q <= hi)
                return float(np.sqrt(np.mean((y[k] - np.interp(q[k], g_q, g_y))**2)))
            fsdp = q[m & (q > 1.0) & (q < 2.2)][np.argmax(S[m & (q > 1.0) & (q < 2.2)])]
            w(f'| {s} | {rmsd(1,10):.3f} | {rmsd(1.2,2.0):.3f} | {fsdp:.2f} A^-1 |')
        w('')

    with open(OUT, 'w') as fh:
        fh.write('\n'.join(L))
    print(f'wrote {OUT}')


def _grimley():
    path = os.path.join(io.BASE_DIR, 'References', 'Grimley_Sq.csv')
    if not os.path.exists(path):
        return None
    d = np.genfromtxt(path, delimiter=',', names=True)
    return d[d.dtype.names[0]], d[d.dtype.names[1]]


if __name__ == '__main__':
    main()
